services:

  minio:
    image: minio/minio:RELEASE.2024-12-13T22-19-12Z
    environment:
      - "MINIO_ROOT_USER=${MINIO__ACCESS_KEY:-admin}"
      - "MINIO_ROOT_PASSWORD=${MINIO__SECRET_KEY:-s3cr3t_p4ssw0rd}"
      - "MINIO_DEFAULT_BUCKETS=${MINIO__BUCKET:-flame}"
    command: ["server", "start"]
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17.2
    environment:
      - "POSTGRES_USER=${POSTGRES__USER:-flame}"
      - "POSTGRES_PASSWORD=${POSTGRES__PASSWORD:-s3cr3t_p4ssw0rd}"
      - "POSTGRES_DB=${POSTGRES__DB:-flame}"

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    environment:
      - "KC_BOOTSTRAP_ADMIN_USERNAME=admin"
      - "KC_BOOTSTRAP_ADMIN_PASSWORD=s3cr3t_p4ssw0rd"
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./docker/keycloak/import:/opt/keycloak/data/import

  node-storage-service:
    build: .
    depends_on:
      - minio
      - postgres
      - keycloak
    environment:
      - "HUB__CORE_BASE_URL=https://core.privateaim.dev"
      - "HUB__STORAGE_BASE_URL=https://storage.privateaim.dev"
      - "HUB__AUTH_BASE_URL=https://auth.privateaim.dev"
      - "HUB__AUTH__FLOW=client"
      - "HUB__AUTH__ID=${HUB__AUTH__ID}"
      - "HUB__AUTH__SECRET=${HUB__AUTH__SECRET}"
      - "MINIO__ENDPOINT=minio:9000"
      - "MINIO__ACCESS_KEY=${MINIO__ACCESS_KEY:-admin}"
      - "MINIO__SECRET_KEY=${MINIO__SECRET_KEY:-s3cr3t_p4ssw0rd}"
      - "MINIO__BUCKET=${MINIO__BUCKET:-flame}"
      - "MINIO__USE_SSL=0"
      - "POSTGRES__HOST=postgres"
      - "POSTGRES__USER=${POSTGRES__USER:-flame}"
      - "POSTGRES__PASSWORD=${POSTGRES__PASSWORD:-s3cr3t_p4ssw0rd}"
      - "POSTGRES__DB=${POSTGRES__DB:-flame}"
      - "OIDC__CERTS_URL=http://keycloak:8080/realms/flame/protocol/openid-connect/certs"
      - "OIDC__CLIENT_ID_CLAIM_NAME=client_id"
      - "CRYPTO__PROVIDER=file"
      - "CRYPTO__ECDH_PRIVATE_KEY_PATH=/app/ecdh.pfx"
    volumes:
      - ./tests/assets/alice.pfx:/app/ecdh.pfx
    ports:
      - "8080:8080"
