apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-storage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-storage
  template:
    metadata:
      labels:
        app: node-storage
    spec:
      containers:
        - name: node-storage-service
          image: ghcr.io/privateaim/node-storage-service:sha-f0d2d9c
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http-storage-srv
          env:
            - name: MINIO__ENDPOINT
              value: local-minio-service:9000
            - name: MINIO__ACCESS_KEY
              value: admin
            - name: MINIO__SECRET_KEY
              value: s3cr3t_p4ssw0rd
            - name: MINIO__USE_SSL
              value: "false"
            - name: MINIO__BUCKET
              value: flame
            - name: HUB__AUTH_USERNAME
              value: your_hub_username_here
            - name: HUB__AUTH_PASSWORD
              value: your_hub_password_here
            - name: OIDC__CERTS_URL
              value: http://keycloak:8080/bla/bla
            # Change this to "1" for testing purposes. This will cause the value of OIDC__CERTS_URL to be
            # ignored. You will still need to set this variable for the service to start up correctly.
            - name: OIDC__SKIP_JWT_VALIDATION
              value: "0"
          startupProbe:
            httpGet:
              path: /healthz
              port: http-storage-srv
            failureThreshold: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http-storage-srv
            failureThreshold: 3
            periodSeconds: 10
