apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-node-storage-service"
spec:
  type: NodePort  # setting nodePort later is optional
  selector:
    app: node-storage
  ports:
    - protocol: TCP
      port: 8080  # port of this service
      targetPort: http-storage  # port on the pod
