name: Merge Dependabot PRs automatically

on:
  workflow_run:
    workflows:
      - "Integration test"
      - "Lint OpenAPI schema file with Spectral"
    types:
      - completed
    branches:
      - main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.actor.login == 'dependabot[bot]' &&
      ${{ length(github.event.workflow_run.pull_requests) > 0}}
    steps:
      - name: Auto-merge Dependabot's PRs
        run: gh pr merge --auto --merge "$PR_NUMBER" --repo "${{ github.repository }}"
        env:
          PR_NUMBER: ${{github.event.workflow_run.pull_requests[0].number}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
