name: Merge Dependabot PRs automatically

on:
  workflow_run:
    workflows:
      - "Integration test"
      - "Lint OpenAPI schema file with Spectral"
    types:
      - completed
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.pull_requests &&
      github.event.workflow_run.pull_requests[0] != null &&
      github.event.workflow_run.pull_requests[0].user.login == 'dependabot[bot]'
    steps:
      - name: Auto-merge Dependabot's PRs
        run: gh pr merge --auto --merge "$PR_NUMBER" --repo "${{ github.repository }}"
        env:
          PR_NUMBER: ${{github.event.workflow_run.pull_requests[0].number}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
